config/routes.rb
Treebook::Application.routes.draw do
  resources :pictures

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end
  
  resources :user do
     post :block
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
   @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>	

<% if signed_in? %>
<div id="friend-status">
	<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user)%>
		<%= link_to "Edit Friendship", edit_user_friendship_path(UserFriendship.where(friend_id: @user).first), class: 'btn' %>
	<% else %>
		<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn', id: 'add-friendship', data: { friend_id: @user.to_param } %>
	<% end %>
</div>
<div id="block-status">
	<% if !(current_user.friends.include?(@user) || current_user.pending_friends.include?(@user))%>
		<% if current_user.blocked_friends.include?(@user) %>
			<%= link_to "Unblock User", edit_user_friendship_path(UserFriendship.where(friend_id: @user).first), class: 'btn' %>
		<% else %>
			<%= link_to "Block User", block_user_friendship_path(friend_id: @user), class: 'btn btn-danger', id: 'block-user', data: { friend_id: @user.id.to_param } %>
		<% end %>
	<% end %>
</div>
<% end %>

<% if @statuses %>
	<% @statuses.each do |status| %>
	<div class="well">
		<%= status.content %>
		<hr />
		<%= link_to time_ago_in_words(status.created_at) %>
	</div>
	<% end %>
<% end %>